### ISSUE TITLE
Electron 24 & 25 is EOL

### ISSUE THREAD

**Issue by gaykitty** [SchildiChat/schildichat-desktop#215]
The version of Element desktop that Schildichat pulls in depends on Election 24 which is [now EOL](https://www.electronjs.org/docs/latest/tutorial/electron-timelines). This should be updated asap.

**Comment by AlbeyAmakiir** [comment]
On Arch Linux, electron24 has been removed from the repos.

**Comment by su-ex** [comment]
I guess this should be solved now.

**Comment by AlbeyAmakiir** [comment]
Why? The package on the arch repos is still asking for the old electron which the arch repos removed. That seems like the problem is still there.

**Comment by su-ex** [comment]
Because it's updated: https://github.com/SchildiChat/element-desktop/blob/fb2931eb808d99995a4cd5ef168e8d4697f39e3f/package.json#L92

**Comment by AlbeyAmakiir** [comment]
Oh, it's set to 25. Which is also EOL now. I guess that's a separate issue, tho?

**Comment by kescherCode** [comment]
According to the comment right above the above, Electron 29 also works. And according to my tests, so do 30 and 31.

Viewing voice messages crashes SchildiChat with Electron 28, so you should avoid using it now.

31 works fine, so I suggest using that for now.
